Change python to python3 for Ubuntu apt install
"python" isn't available in Ubuntu 24.10:

```
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  2to3  python-is-python3

Error: Package 'python' has no installation candidate
```