Update some dependencies (#2575)
* Update some dependencies

* Fix weird errors with the data-grid mock not working, but appear not to be required anyways

* Pin @oclif/plugin-help to 3.2.14

Otherwise would get errors

on v3.2.18

TypeError: HelpClass is not a constructor

on v3.3.0

 ›   Error: Please implement `formatCommand` in your custom help class.
 ›   See https://oclif.io/docs/help_classes for more.

* Use @fontsource/roboto